lit-analyzer: ignore type-only imports
runem/lit-analyzer pull request #139
Opened 2020-08-29 21:37 UTC by 43081j

fixes #137.

this looks like it might be ok to sort the issue. let me know if you see anything wrong with it @runem

2020-11-07 09:41 UTC, 43081j commented
@runem do we still need this / can we push ahead with it some time? would be nice to avoid it going stale

2021-05-09 16:58 UTC, justinfagnani commented
@43081j I think this is a reasonable approach... a type-only import doesn't seem to fit the idea of a direct import in any sense.

2021-05-09 17:01 UTC, justinfagnani requested changes

2021-05-09 17:01 UTC, justinfagnani commented on packages/lit-analyzer/src/analyze/parse/parse-dependencies/visit-dependencies.ts
> +	if ((context.ts.isImportDeclaration(node) && !node.importClause?.isTypeOnly) || context.ts.isExportDeclaration(node)) {
I think you should handle type-only exports here as well.

2021-05-09 18:56 UTC, 43081j commented
@justinfagnani I've updated with a check for type only exports, if you don't mind taking another look when you get chance

2021-05-10 01:09 UTC, justinfagnani approved these changes

2021-05-10 01:09 UTC, merged